In [3]:
%load_ext autoreload
%autoreload 2

import tensorflow as tf
import numpy as np

from tfga import GeometricAlgebra

In [4]:
sta = GeometricAlgebra([1, -1, -1, -1])

In [5]:
sta.print(sta.geom_prod(sta.e("0"), sta.e("1")))
a = sta.geom_prod(sta.e("0"), sta.from_scalar(4.0))
b = sta.geom_prod(sta.from_scalar(9.0), sta.e("1"))
sta.print(a)
sta.print(b)
sta.print(a, b)
sta.print(
    sta.e("0"),
    sta.e("1"),
    sta.e("0", "1"),
    sta.e("01"),
    sta.e("10")
)

MultiVector[1.00*e_01]
MultiVector[4.00*e_0]
MultiVector[9.00*e_1]
MultiVector[4.00*e_0] MultiVector[9.00*e_1]
MultiVector[1.00*e_0] MultiVector[1.00*e_1] MultiVector[1.00*e_0 + 1.00*e_1] MultiVector[1.00*e_01] MultiVector[-1.00*e_01]


In [6]:
sta.print("a:", a)
sta.print("~a:", sta.reversion(a))
sta.print("inv a:", sta.inverse(a))
sta.print("b:", b)
sta.print("~b:", sta.reversion(b))
sta.print("inv b:", sta.inverse(b))

a: MultiVector[4.00*e_0]
~a: MultiVector[4.00*e_0]
inv a: MultiVector[0.25*e_0]
b: MultiVector[9.00*e_1]
~b: MultiVector[9.00*e_1]
inv b: MultiVector[-0.11*e_1]


In [7]:
c = sta.geom_prod(a, b)
sta.print("c = a * b:", c)
sta.print("c * c^-1:", sta.geom_prod(c, sta.inverse(c)))
sta.print("a * a^-1", sta.geom_prod(a, sta.inverse(a)))
sta.print("b * b^-1:", sta.geom_prod(b, sta.inverse(b)))
a_inv_c = sta.geom_prod(sta.inverse(a), c)
sta.print("a^-1 * c:", a_inv_c, "should be b:", b, tf.reduce_all(a_inv_c == b))
c_b_inv = sta.geom_prod(c, sta.inverse(b))
sta.print("c * b^-1:", c_b_inv, "should be a:", a, tf.reduce_all(c_b_inv == a))

c = a * b: MultiVector[36.00*e_01]
c * c^-1: MultiVector[1.00*1]
a * a^-1 MultiVector[1.00*1]
b * b^-1: MultiVector[1.00*1]
a^-1 * c: MultiVector[9.00*e_1] should be b: MultiVector[9.00*e_1] tf.Tensor(True, shape=(), dtype=bool)
c * b^-1: MultiVector[4.00*e_0] should be a: MultiVector[4.00*e_0] tf.Tensor(True, shape=(), dtype=bool)


In [8]:
d = sta.geom_prod(a, b) + b
sta.print(d)

MultiVector[9.00*e_1 + 36.00*e_01]


In [9]:
sta.print(sta.inner_prod(a, b))
sta.print(sta.ext_prod(a, b))

MultiVector[]
MultiVector[36.00*e_01]


In [10]:
m = tf.ones(16)
sta.print("m:", m)
sta.print("~m:", sta.reversion(m))
sta.print("bar m:", sta.conjugation(m))
sta.print("bar~m:", sta.grade_automorphism(m))

m: MultiVector[1.00*1 + 1.00*e_0 + 1.00*e_1 + 1.00*e_2 + 1.00*e_3 + 1.00*e_01 + 1.00*e_02 + 1.00*e_03 + 1.00*e_12 + 1.00*e_13 + 1.00*e_23 + 1.00*e_012 + 1.00*e_013 + 1.00*e_023 + 1.00*e_123 + 1.00*e_0123]
~m: MultiVector[1.00*1 + 1.00*e_0 + 1.00*e_1 + 1.00*e_2 + 1.00*e_3 + -1.00*e_01 + -1.00*e_02 + -1.00*e_03 + -1.00*e_12 + -1.00*e_13 + -1.00*e_23 + -1.00*e_012 + -1.00*e_013 + -1.00*e_023 + -1.00*e_123 + 1.00*e_0123]
bar m: MultiVector[1.00*1 + -1.00*e_0 + -1.00*e_1 + -1.00*e_2 + -1.00*e_3 + -1.00*e_01 + -1.00*e_02 + -1.00*e_03 + -1.00*e_12 + -1.00*e_13 + -1.00*e_23 + 1.00*e_012 + 1.00*e_013 + 1.00*e_023 + 1.00*e_123 + 1.00*e_0123]
bar~m: MultiVector[1.00*1 + -1.00*e_0 + -1.00*e_1 + -1.00*e_2 + -1.00*e_3 + 1.00*e_01 + 1.00*e_02 + 1.00*e_03 + 1.00*e_12 + 1.00*e_13 + 1.00*e_23 + -1.00*e_012 + -1.00*e_013 + -1.00*e_023 + -1.00*e_123 + 1.00*e_0123]


In [11]:
complex_ga = GeometricAlgebra([1, 1])
print(complex_ga.basis_mvs)

tf.Tensor(
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]], shape=(2, 4), dtype=float32)


In [12]:
x = complex_ga.from_scalar(5.0)
imag = complex_ga.e("01")
r = complex_ga.approx_exp(complex_ga.geom_prod(complex_ga.from_scalar(45.0), imag))
complex_ga.print("x:", x)
complex_ga.print("e1:", complex_ga.basis_mvs[0])
complex_ga.print("e2:", complex_ga.basis_mvs[1])
complex_ga.print("i:", imag)
complex_ga.print("i^2:", complex_ga.geom_prod(imag, imag))
complex_ga.print("r = e^(45° * e12):", r)
complex_ga.print("x * r (x rotated 45°):", complex_ga.geom_prod(x, r))
complex_ga.print("x * ~r (x rotated -45°):", complex_ga.geom_prod(x, complex_ga.reversion(r)))

x: MultiVector[5.00*1]
e1: MultiVector[1.00*e_0]
e2: MultiVector[1.00*e_1]
i: MultiVector[1.00*e_01]
i^2: MultiVector[-1.00*1]
r = e^(45° * e12): MultiVector[nan*1 + nan*e_0 + nan*e_1 + nan*e_01]
x * r (x rotated 45°): MultiVector[nan*1 + nan*e_0 + nan*e_1 + nan*e_01]
x * ~r (x rotated -45°): MultiVector[nan*1 + nan*e_0 + nan*e_1 + nan*e_01]


In [13]:
for i in range(9):
    complex_ga.print(i, "%d°" % (i * 45), complex_ga.int_pow(r, i))

0 0° MultiVector[1.00*1]
1 45° MultiVector[nan*1 + nan*e_0 + nan*e_1 + nan*e_01]
2 90° MultiVector[nan*1 + nan*e_0 + nan*e_1 + nan*e_01]
3 135° MultiVector[nan*1 + nan*e_0 + nan*e_1 + nan*e_01]
4 180° MultiVector[nan*1 + nan*e_0 + nan*e_1 + nan*e_01]
5 225° MultiVector[nan*1 + nan*e_0 + nan*e_1 + nan*e_01]
6 270° MultiVector[nan*1 + nan*e_0 + nan*e_1 + nan*e_01]
7 315° MultiVector[nan*1 + nan*e_0 + nan*e_1 + nan*e_01]
8 360° MultiVector[nan*1 + nan*e_0 + nan*e_1 + nan*e_01]


In [14]:
complex_ga.print(complex_ga.int_pow(r, 25))

MultiVector[nan*1 + nan*e_0 + nan*e_1 + nan*e_01]


In [19]:
y = complex_ga.from_scalar(0.8)
complex_ga.print(y)
complex_ga.print(complex_ga.approx_log(y), "expected", np.log(0.8))
complex_ga.print(complex_ga.approx_exp(complex_ga.approx_log(y)), "expected", 0.8)
complex_ga.print(complex_ga.approx_log(complex_ga.approx_exp(y)), "expected", 0.8) # doesn't work because approx_log only works for |x -1| < 1

MultiVector[0.80*1]
MultiVector[-0.22*1] expected -0.2231435513142097
MultiVector[0.80*1] expected 0.8
MultiVector[-283.90*1] expected 0.8


In [24]:
u = tf.tile(tf.expand_dims(a, axis=0), [3, 1])
sta.print(u)
sta.print(u[0])

MultiVector[batch_shape=(3,)]
MultiVector[4.00*e_0]


In [40]:
v = sta.from_tensor_with_kind(tf.ones(16, dtype=tf.float32), "mv")
sta.print(v)
sta.print(sta.keep_blades(v, ["10", "1"]))
sta.print(sta.keep_blades(v, "2"))
sta.print("R:", sta.select_blades(v, ["0", "01", "10"]))
sta.print("R:", sta.select_blades(v, ["123", "01", "0", "0"]))
sta.print("R:", sta.select_blades(v, "312"))
sta.print(v[..., 0])

MultiVector[1.00*1 + 1.00*e_0 + 1.00*e_1 + 1.00*e_2 + 1.00*e_3 + 1.00*e_01 + 1.00*e_02 + 1.00*e_03 + 1.00*e_12 + 1.00*e_13 + 1.00*e_23 + 1.00*e_012 + 1.00*e_013 + 1.00*e_023 + 1.00*e_123 + 1.00*e_0123]
MultiVector[1.00*e_1 + 1.00*e_01]
MultiVector[1.00*e_2]
R: tf.Tensor([ 1.  1. -1.], shape=(3,), dtype=float32)
R: tf.Tensor([1. 1. 1. 1.], shape=(4,), dtype=float32)
R: tf.Tensor([1. 1. 1.], shape=(3,), dtype=float32)
tf.Tensor(1.0, shape=(), dtype=float32)
